name: Deploy Sanity
on:
  push:
    branches: [main]
jobs:
  sanity-deploy:
    runs-on: ubuntu-18.04
    name: Deploy Sanity
    defaults:
      run:
        working-directory: studio
    steps:
      - uses: actions/checkout@v2
      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14.x
      - uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: deploy
